import * as cornerstone from '@cornerstonejs/core';
import * as cornerstoneTools from '@cornerstonejs/tools';
import dicomParser from 'dicom-parser';
import cornerstoneDICOMImageLoader from '@cornerstonejs/dicom-image-loader';
import {
    cornerstoneStreamingImageVolumeLoader,
    cornerstoneStreamingDynamicImageVolumeLoader,
} from '@cornerstonejs/streaming-image-volume-loader';

// ======== Set up page ======== //
const size = '500px';

const content = document.getElementById('content');

const title = document.createElement('h1');
title.innerText = "DICOM Curation Tools";
content.append(title);

const description = document.createElement('h2');
description.innerText = "A visualization tool for DICOM curation";
content.append(description);

const viewportGrid = document.createElement('div');

viewportGrid.style.display = 'flex';
viewportGrid.style.flexDirection = 'row';

const element1 = document.createElement('div');
const element2 = document.createElement('div');
const element3 = document.createElement('div');

// Disable right click context menu
element1.oncontextmenu = () => false;
element2.oncontextmenu = () => false;
element3.oncontextmenu = () => false;

element1.style.width = size;
element1.style.height = size;
element2.style.width = size;
element2.style.height = size;
element3.style.width = size;
element3.style.height = size;

viewportGrid.appendChild(element1);
viewportGrid.appendChild(element2);
viewportGrid.appendChild(element3);

content.appendChild(viewportGrid);

// ============================= //

async function run(input_type) {
    await cornerstone.init();
    initCornerstoneDICOMImageLoader();
    initVolumeLoader();
    await cornerstoneTools.init();

    const volumeId = 'cornerstoneStreamingImageVolume: myVolume';

    const volume = await cornerstone.volumeLoader.createAndCacheVolume(volumeId, {
        imageIds: getDICOMVolume(),
    });

    const viewportId1 = 'VP_AXIAL';
    const viewportId2 = 'VP_SAGITTAL';
    const viewportId3 = 'VP_CORONAL';
    
    const renderingEngineId = 'myRenderingEngine';
    const renderingEngine = new cornerstone.RenderingEngine(renderingEngineId);

    const viewportInputArray = [
        {
            viewportId: viewportId1,
            type: cornerstone.Enums.ViewportType.ORTHOGRAPHIC,
            element: element1,
            defaultOptions: {
                orientation: cornerstone.Enums.OrientationAxis.AXIAL,
                VOILUTFunction: cornerstone.Enums.VOILUTFunctionType.LINEAR,
            },
        },
        {
            viewportId: viewportId2,
            type: cornerstone.Enums.ViewportType.ORTHOGRAPHIC,
            element: element2,
            defaultOptions: {
                orientation: cornerstone.Enums.OrientationAxis.SAGITTAL,
                VOILUTFunction: cornerstone.Enums.VOILUTFunctionType.LINEAR,
            },
        },
        {
            viewportId: viewportId3,
            type: cornerstone.Enums.ViewportType.ORTHOGRAPHIC,
            element: element3,
            defaultOptions: {
                orientation: cornerstone.Enums.OrientationAxis.CORONAL,
                VOILUTFunction: cornerstone.Enums.VOILUTFunctionType.LINEAR,
            },
        },
    ];

    renderingEngine.setViewports(viewportInputArray);

    volume.load();

    await cornerstone.setVolumesForViewports(
        renderingEngine,
        [
            {
                volumeId: volumeId,
                callback: ({ volumeActor }) => {
                    volumeActor
                        .getProperty()
                        .getRGBTransferFunction(0)
                        .setMappingRange(-180, 220);
                },
                //slabThickness: 0.1,
            }
        ],
        viewportInputArray.map(v => v.viewportId)
    );
    
    // Tools setup
    // --------------------------------
    const toolGroupId = 'defaultToolGroup';
    const toolGroup = cornerstoneTools.ToolGroupManager.createToolGroup(toolGroupId);

    cornerstoneTools.addTool(cornerstoneTools.StackScrollMouseWheelTool);
    cornerstoneTools.addTool(cornerstoneTools.SegmentationDisplayTool);
    cornerstoneTools.addTool(cornerstoneTools.ZoomTool);
    cornerstoneTools.addTool(cornerstoneTools.WindowLevelTool);

    toolGroup.addTool(cornerstoneTools.StackScrollMouseWheelTool.toolName);
    toolGroup.addTool(cornerstoneTools.SegmentationDisplayTool.toolName);
    toolGroup.addTool(cornerstoneTools.ZoomTool.toolName);
    toolGroup.addTool(cornerstoneTools.WindowLevelTool.toolName);

    toolGroup.addViewport(viewportId1, renderingEngineId);
    toolGroup.addViewport(viewportId2, renderingEngineId);
    toolGroup.addViewport(viewportId3, renderingEngineId);

    toolGroup.setToolActive(cornerstoneTools.StackScrollMouseWheelTool.toolName);
    toolGroup.setToolEnabled(cornerstoneTools.SegmentationDisplayTool.toolName);
    toolGroup.setToolActive(cornerstoneTools.WindowLevelTool.toolName, {
        bindings: [
            {
                mouseButton: cornerstoneTools.Enums.MouseBindings.Primary, // Left Click
            },
        ],
    });
    toolGroup.setToolActive(cornerstoneTools.ZoomTool.toolName, {
        bindings: [
            {
                mouseButton: cornerstoneTools.Enums.MouseBindings.Secondary, // Right Click
            },
        ],
    });


    // Seg setup
    // --------------------------------
    //const segmentationId = 'nifti:' + getNiftiSeg();

    //const segVolume = await cornerstone.volumeLoader.createAndCacheDerivedSegmentationVolume(volumeId, {
    //    volumeId: segmentationId,
    //});

    //// Add the segmentations to state
    //cornerstoneTools.segmentation.addSegmentations([
    //    {
    //        segmentationId,
    //        representation: {
    //            type: cornerstoneTools.Enums.SegmentationRepresentations.Labelmap,
    //            data: {
    //                volumeId: segmentationId,
    //            },
    //        },
    //    },
    //]);

    //const toolGroupConfiguration = {
    //    renderInactiveSegmentations: true,
    //    representations: {
    //        //https://www.cornerstonejs.org/api/tools/namespace/Types#LabelmapConfig
    //        LABELMAP: {
    //            renderFill: true,
    //            renderOutline: true,
    //            fillAlpha: 0.5,
    //        },
    //    },
    //}
    //cornerstoneTools.segmentation.config.setToolGroupSpecificConfig(toolGroupId, toolGroupConfiguration)
    

    ////const colorLUT = [
    ////    [0, 0, 0, 0], // Assume background is transparent
    ////    [255, 0, 0, 255], // Label 1: Red
    ////    [0, 255, 0, 255], // Label 2: Green
    ////    // Add more colors for additional labels
    ////];

    ////const colors = [
    ////    [255, 0, 0],
    ////    [0, 255, 0],
    ////    [128, 0, 0],
    ////    [0, 0, 255],
    ////    [0, 128, 0],
    ////    [255, 255, 0],
    ////    [0, 255, 255],
    ////    [0, 0, 0],
    ////    [0, 0, 128],
    ////    [255, 0, 255],
    ////];

    ////segmentation.setColorLUT(renderingEngineId, segVolume.volumeId, colorLUT);

    //// Activate the segmentation display for each viewport
    ////const viewports = renderingEngine.getViewports();
    ////viewports.forEach((viewport) => {
    ////    segmentation.setSegmentationActive(renderingEngineId, viewport.viewportId, true);
    ////});

    //await cornerstoneTools.segmentation.addSegmentationRepresentations(toolGroupId, [
    //    {
    //        segmentationId,
    //        type: cornerstoneTools.Enums.SegmentationRepresentations.Labelmap,
    //    },
    //]);

    //const activeSeg = cornerstoneTools.segmentation.getActiveSegmentationRepresentation(toolGroupId);

    // --------------------------------
        
    //renderingEngine.render();
    renderingEngine.renderViewports([viewportId1, viewportId2, viewportId3]);
}

function initVolumeLoader() {
    cornerstone.volumeLoader.registerUnknownVolumeLoader(
        cornerstoneStreamingImageVolumeLoader
    );
    cornerstone.volumeLoader.registerVolumeLoader(
        'cornerstoneStreamingImageVolume',
        cornerstoneStreamingImageVolumeLoader
    );
    cornerstone.volumeLoader.registerVolumeLoader(
        'cornerstoneStreamingDynamicImageVolume',
        cornerstoneStreamingDynamicImageVolumeLoader
    );
}


function initCornerstoneDICOMImageLoader() {
    const { preferSizeOverAccuracy, useNorm16Texture } = cornerstone.getConfiguration().rendering;
    cornerstoneDICOMImageLoader.external.cornerstone = cornerstone;
    cornerstoneDICOMImageLoader.external.dicomParser = dicomParser;
    cornerstoneDICOMImageLoader.configure({
        useWebWorkers: true,
        decodeConfig: {
            convertFloatPixelDataToInt: false,
            use16BitDataType: preferSizeOverAccuracy || useNorm16Texture,
        },
    });

    let maxWebWorkers = 1;

    if (navigator.hardwareConcurrency) {
        maxWebWorkers = Math.min(navigator.hardwareConcurrency, 7);
    }

    var config = {
        maxWebWorkers,
        startWebWorkersOnDemand: false,
        taskConfiguration: {
            decodeTask: {
                initializeCodecsOnStartup: false,
                strict: false,
            },
        },
    };

    cornerstoneDICOMImageLoader.webWorkerManager.initialize(config);
}

//function getDICOMVolume() {//{{{
//    return [
//        'wadouri:/dicom/full_body_ct/1-001.dcm',
//        'wadouri:/dicom/full_body_ct/1-002.dcm',
//        'wadouri:/dicom/full_body_ct/1-003.dcm',
//        'wadouri:/dicom/full_body_ct/1-004.dcm',
//        'wadouri:/dicom/full_body_ct/1-005.dcm',
//        'wadouri:/dicom/full_body_ct/1-006.dcm',
//        'wadouri:/dicom/full_body_ct/1-007.dcm',
//        'wadouri:/dicom/full_body_ct/1-008.dcm',
//        'wadouri:/dicom/full_body_ct/1-009.dcm',
//        'wadouri:/dicom/full_body_ct/1-010.dcm',
//        'wadouri:/dicom/full_body_ct/1-011.dcm',
//        'wadouri:/dicom/full_body_ct/1-012.dcm',
//        'wadouri:/dicom/full_body_ct/1-013.dcm',
//        'wadouri:/dicom/full_body_ct/1-014.dcm',
//        'wadouri:/dicom/full_body_ct/1-015.dcm',
//        'wadouri:/dicom/full_body_ct/1-016.dcm',
//        'wadouri:/dicom/full_body_ct/1-017.dcm',
//        'wadouri:/dicom/full_body_ct/1-018.dcm',
//        'wadouri:/dicom/full_body_ct/1-019.dcm',
//        'wadouri:/dicom/full_body_ct/1-020.dcm',
//        'wadouri:/dicom/full_body_ct/1-021.dcm',
//        'wadouri:/dicom/full_body_ct/1-022.dcm',
//        'wadouri:/dicom/full_body_ct/1-023.dcm',
//        'wadouri:/dicom/full_body_ct/1-024.dcm',
//        'wadouri:/dicom/full_body_ct/1-025.dcm',
//        'wadouri:/dicom/full_body_ct/1-026.dcm',
//        'wadouri:/dicom/full_body_ct/1-027.dcm',
//        'wadouri:/dicom/full_body_ct/1-028.dcm',
//        'wadouri:/dicom/full_body_ct/1-029.dcm',
//        'wadouri:/dicom/full_body_ct/1-030.dcm',
//        'wadouri:/dicom/full_body_ct/1-031.dcm',
//        'wadouri:/dicom/full_body_ct/1-032.dcm',
//        'wadouri:/dicom/full_body_ct/1-033.dcm',
//        'wadouri:/dicom/full_body_ct/1-034.dcm',
//        'wadouri:/dicom/full_body_ct/1-035.dcm',
//        'wadouri:/dicom/full_body_ct/1-036.dcm',
//        'wadouri:/dicom/full_body_ct/1-037.dcm',
//        'wadouri:/dicom/full_body_ct/1-038.dcm',
//        'wadouri:/dicom/full_body_ct/1-039.dcm',
//        'wadouri:/dicom/full_body_ct/1-040.dcm',
//        'wadouri:/dicom/full_body_ct/1-041.dcm',
//        'wadouri:/dicom/full_body_ct/1-042.dcm',
//        'wadouri:/dicom/full_body_ct/1-043.dcm',
//        'wadouri:/dicom/full_body_ct/1-044.dcm',
//        'wadouri:/dicom/full_body_ct/1-045.dcm',
//        'wadouri:/dicom/full_body_ct/1-046.dcm',
//        'wadouri:/dicom/full_body_ct/1-047.dcm',
//        'wadouri:/dicom/full_body_ct/1-048.dcm',
//        'wadouri:/dicom/full_body_ct/1-049.dcm',
//        'wadouri:/dicom/full_body_ct/1-050.dcm',
//        'wadouri:/dicom/full_body_ct/1-051.dcm',
//        'wadouri:/dicom/full_body_ct/1-052.dcm',
//        'wadouri:/dicom/full_body_ct/1-053.dcm',
//        'wadouri:/dicom/full_body_ct/1-054.dcm',
//        'wadouri:/dicom/full_body_ct/1-055.dcm',
//        'wadouri:/dicom/full_body_ct/1-056.dcm',
//        'wadouri:/dicom/full_body_ct/1-057.dcm',
//        'wadouri:/dicom/full_body_ct/1-058.dcm',
//        'wadouri:/dicom/full_body_ct/1-059.dcm',
//        'wadouri:/dicom/full_body_ct/1-060.dcm',
//        'wadouri:/dicom/full_body_ct/1-061.dcm',
//        'wadouri:/dicom/full_body_ct/1-062.dcm',
//        'wadouri:/dicom/full_body_ct/1-063.dcm',
//        'wadouri:/dicom/full_body_ct/1-064.dcm',
//        'wadouri:/dicom/full_body_ct/1-065.dcm',
//        'wadouri:/dicom/full_body_ct/1-066.dcm',
//        'wadouri:/dicom/full_body_ct/1-067.dcm',
//        'wadouri:/dicom/full_body_ct/1-068.dcm',
//        'wadouri:/dicom/full_body_ct/1-069.dcm',
//        'wadouri:/dicom/full_body_ct/1-070.dcm',
//        'wadouri:/dicom/full_body_ct/1-071.dcm',
//        'wadouri:/dicom/full_body_ct/1-072.dcm',
//        'wadouri:/dicom/full_body_ct/1-073.dcm',
//        'wadouri:/dicom/full_body_ct/1-074.dcm',
//        'wadouri:/dicom/full_body_ct/1-075.dcm',
//        'wadouri:/dicom/full_body_ct/1-076.dcm',
//        'wadouri:/dicom/full_body_ct/1-077.dcm',
//        'wadouri:/dicom/full_body_ct/1-078.dcm',
//        'wadouri:/dicom/full_body_ct/1-079.dcm',
//        'wadouri:/dicom/full_body_ct/1-080.dcm',
//        'wadouri:/dicom/full_body_ct/1-081.dcm',
//        'wadouri:/dicom/full_body_ct/1-082.dcm',
//        'wadouri:/dicom/full_body_ct/1-083.dcm',
//        'wadouri:/dicom/full_body_ct/1-084.dcm',
//        'wadouri:/dicom/full_body_ct/1-085.dcm',
//        'wadouri:/dicom/full_body_ct/1-086.dcm',
//        'wadouri:/dicom/full_body_ct/1-087.dcm',
//        'wadouri:/dicom/full_body_ct/1-088.dcm',
//        'wadouri:/dicom/full_body_ct/1-089.dcm',
//        'wadouri:/dicom/full_body_ct/1-090.dcm',
//        'wadouri:/dicom/full_body_ct/1-091.dcm',
//        'wadouri:/dicom/full_body_ct/1-092.dcm',
//        'wadouri:/dicom/full_body_ct/1-093.dcm',
//        'wadouri:/dicom/full_body_ct/1-094.dcm',
//        'wadouri:/dicom/full_body_ct/1-095.dcm',
//        'wadouri:/dicom/full_body_ct/1-096.dcm',
//        'wadouri:/dicom/full_body_ct/1-097.dcm',
//        'wadouri:/dicom/full_body_ct/1-098.dcm',
//        'wadouri:/dicom/full_body_ct/1-099.dcm',
//        'wadouri:/dicom/full_body_ct/1-100.dcm',
//        'wadouri:/dicom/full_body_ct/1-101.dcm',
//        'wadouri:/dicom/full_body_ct/1-102.dcm',
//        'wadouri:/dicom/full_body_ct/1-103.dcm',
//        'wadouri:/dicom/full_body_ct/1-104.dcm',
//        'wadouri:/dicom/full_body_ct/1-105.dcm',
//        'wadouri:/dicom/full_body_ct/1-106.dcm',
//        'wadouri:/dicom/full_body_ct/1-107.dcm',
//        'wadouri:/dicom/full_body_ct/1-108.dcm',
//        'wadouri:/dicom/full_body_ct/1-109.dcm',
//        'wadouri:/dicom/full_body_ct/1-110.dcm',
//        'wadouri:/dicom/full_body_ct/1-111.dcm',
//        'wadouri:/dicom/full_body_ct/1-112.dcm',
//        'wadouri:/dicom/full_body_ct/1-113.dcm',
//        'wadouri:/dicom/full_body_ct/1-114.dcm',
//        'wadouri:/dicom/full_body_ct/1-115.dcm',
//        'wadouri:/dicom/full_body_ct/1-116.dcm',
//        'wadouri:/dicom/full_body_ct/1-117.dcm',
//        'wadouri:/dicom/full_body_ct/1-118.dcm',
//        'wadouri:/dicom/full_body_ct/1-119.dcm',
//        'wadouri:/dicom/full_body_ct/1-120.dcm',
//        'wadouri:/dicom/full_body_ct/1-121.dcm',
//        'wadouri:/dicom/full_body_ct/1-122.dcm',
//        'wadouri:/dicom/full_body_ct/1-123.dcm',
//        'wadouri:/dicom/full_body_ct/1-124.dcm',
//        'wadouri:/dicom/full_body_ct/1-125.dcm',
//        'wadouri:/dicom/full_body_ct/1-126.dcm',
//        'wadouri:/dicom/full_body_ct/1-127.dcm',
//        'wadouri:/dicom/full_body_ct/1-128.dcm',
//        'wadouri:/dicom/full_body_ct/1-129.dcm',
//        'wadouri:/dicom/full_body_ct/1-130.dcm',
//        'wadouri:/dicom/full_body_ct/1-131.dcm',
//        'wadouri:/dicom/full_body_ct/1-132.dcm',
//        'wadouri:/dicom/full_body_ct/1-133.dcm',
//        'wadouri:/dicom/full_body_ct/1-134.dcm',
//        'wadouri:/dicom/full_body_ct/1-135.dcm',
//        'wadouri:/dicom/full_body_ct/1-136.dcm',
//        'wadouri:/dicom/full_body_ct/1-137.dcm',
//        'wadouri:/dicom/full_body_ct/1-138.dcm',
//        'wadouri:/dicom/full_body_ct/1-139.dcm',
//        'wadouri:/dicom/full_body_ct/1-140.dcm',
//        'wadouri:/dicom/full_body_ct/1-141.dcm',
//        'wadouri:/dicom/full_body_ct/1-142.dcm',
//        'wadouri:/dicom/full_body_ct/1-143.dcm',
//        'wadouri:/dicom/full_body_ct/1-144.dcm',
//        'wadouri:/dicom/full_body_ct/1-145.dcm',
//        'wadouri:/dicom/full_body_ct/1-146.dcm',
//        'wadouri:/dicom/full_body_ct/1-147.dcm',
//        'wadouri:/dicom/full_body_ct/1-148.dcm',
//        'wadouri:/dicom/full_body_ct/1-149.dcm',
//        'wadouri:/dicom/full_body_ct/1-150.dcm',
//        'wadouri:/dicom/full_body_ct/1-151.dcm',
//        'wadouri:/dicom/full_body_ct/1-152.dcm',
//        'wadouri:/dicom/full_body_ct/1-153.dcm',
//        'wadouri:/dicom/full_body_ct/1-154.dcm',
//        'wadouri:/dicom/full_body_ct/1-155.dcm',
//        'wadouri:/dicom/full_body_ct/1-156.dcm',
//        'wadouri:/dicom/full_body_ct/1-157.dcm',
//        'wadouri:/dicom/full_body_ct/1-158.dcm',
//        'wadouri:/dicom/full_body_ct/1-159.dcm',
//        'wadouri:/dicom/full_body_ct/1-160.dcm',
//        'wadouri:/dicom/full_body_ct/1-161.dcm',
//        'wadouri:/dicom/full_body_ct/1-162.dcm',
//        'wadouri:/dicom/full_body_ct/1-163.dcm',
//        'wadouri:/dicom/full_body_ct/1-164.dcm',
//        'wadouri:/dicom/full_body_ct/1-165.dcm',
//        'wadouri:/dicom/full_body_ct/1-166.dcm',
//        'wadouri:/dicom/full_body_ct/1-167.dcm',
//        'wadouri:/dicom/full_body_ct/1-168.dcm',
//        'wadouri:/dicom/full_body_ct/1-169.dcm',
//        'wadouri:/dicom/full_body_ct/1-170.dcm',
//        'wadouri:/dicom/full_body_ct/1-171.dcm',
//        'wadouri:/dicom/full_body_ct/1-172.dcm',
//        'wadouri:/dicom/full_body_ct/1-173.dcm',
//        'wadouri:/dicom/full_body_ct/1-174.dcm',
//        'wadouri:/dicom/full_body_ct/1-175.dcm',
//        'wadouri:/dicom/full_body_ct/1-176.dcm',
//        'wadouri:/dicom/full_body_ct/1-177.dcm',
//        'wadouri:/dicom/full_body_ct/1-178.dcm',
//        'wadouri:/dicom/full_body_ct/1-179.dcm',
//        'wadouri:/dicom/full_body_ct/1-180.dcm',
//        'wadouri:/dicom/full_body_ct/1-181.dcm',
//        'wadouri:/dicom/full_body_ct/1-182.dcm',
//        'wadouri:/dicom/full_body_ct/1-183.dcm',
//        'wadouri:/dicom/full_body_ct/1-184.dcm',
//        'wadouri:/dicom/full_body_ct/1-185.dcm',
//        'wadouri:/dicom/full_body_ct/1-186.dcm',
//        'wadouri:/dicom/full_body_ct/1-187.dcm',
//        'wadouri:/dicom/full_body_ct/1-188.dcm',
//        'wadouri:/dicom/full_body_ct/1-189.dcm',
//        'wadouri:/dicom/full_body_ct/1-190.dcm',
//        'wadouri:/dicom/full_body_ct/1-191.dcm',
//        'wadouri:/dicom/full_body_ct/1-192.dcm',
//        'wadouri:/dicom/full_body_ct/1-193.dcm',
//        'wadouri:/dicom/full_body_ct/1-194.dcm',
//        'wadouri:/dicom/full_body_ct/1-195.dcm',
//        'wadouri:/dicom/full_body_ct/1-196.dcm',
//        'wadouri:/dicom/full_body_ct/1-197.dcm',
//        'wadouri:/dicom/full_body_ct/1-198.dcm',
//        'wadouri:/dicom/full_body_ct/1-199.dcm',
//        'wadouri:/dicom/full_body_ct/1-200.dcm',
//        'wadouri:/dicom/full_body_ct/1-201.dcm',
//        'wadouri:/dicom/full_body_ct/1-202.dcm',
//        'wadouri:/dicom/full_body_ct/1-203.dcm',
//        'wadouri:/dicom/full_body_ct/1-204.dcm',
//        'wadouri:/dicom/full_body_ct/1-205.dcm',
//        'wadouri:/dicom/full_body_ct/1-206.dcm',
//        'wadouri:/dicom/full_body_ct/1-207.dcm',
//        'wadouri:/dicom/full_body_ct/1-208.dcm',
//        'wadouri:/dicom/full_body_ct/1-209.dcm',
//        'wadouri:/dicom/full_body_ct/1-210.dcm',
//        'wadouri:/dicom/full_body_ct/1-211.dcm',
//        'wadouri:/dicom/full_body_ct/1-212.dcm',
//        'wadouri:/dicom/full_body_ct/1-213.dcm',
//        'wadouri:/dicom/full_body_ct/1-214.dcm',
//        'wadouri:/dicom/full_body_ct/1-215.dcm',
//        'wadouri:/dicom/full_body_ct/1-216.dcm',
//        'wadouri:/dicom/full_body_ct/1-217.dcm',
//        'wadouri:/dicom/full_body_ct/1-218.dcm',
//        'wadouri:/dicom/full_body_ct/1-219.dcm',
//        'wadouri:/dicom/full_body_ct/1-220.dcm',
//        'wadouri:/dicom/full_body_ct/1-221.dcm',
//        'wadouri:/dicom/full_body_ct/1-222.dcm',
//        'wadouri:/dicom/full_body_ct/1-223.dcm',
//        'wadouri:/dicom/full_body_ct/1-224.dcm',
//        'wadouri:/dicom/full_body_ct/1-225.dcm',
//        'wadouri:/dicom/full_body_ct/1-226.dcm',
//        'wadouri:/dicom/full_body_ct/1-227.dcm',
//        'wadouri:/dicom/full_body_ct/1-228.dcm',
//        'wadouri:/dicom/full_body_ct/1-229.dcm',
//        'wadouri:/dicom/full_body_ct/1-230.dcm',
//        'wadouri:/dicom/full_body_ct/1-231.dcm',
//        'wadouri:/dicom/full_body_ct/1-232.dcm',
//        'wadouri:/dicom/full_body_ct/1-233.dcm',
//        'wadouri:/dicom/full_body_ct/1-234.dcm',
//        'wadouri:/dicom/full_body_ct/1-235.dcm',
//        'wadouri:/dicom/full_body_ct/1-236.dcm',
//        'wadouri:/dicom/full_body_ct/1-237.dcm',
//        'wadouri:/dicom/full_body_ct/1-238.dcm',
//        'wadouri:/dicom/full_body_ct/1-239.dcm',
//        'wadouri:/dicom/full_body_ct/1-240.dcm',
//        'wadouri:/dicom/full_body_ct/1-241.dcm',
//        'wadouri:/dicom/full_body_ct/1-242.dcm',
//        'wadouri:/dicom/full_body_ct/1-243.dcm',
//        'wadouri:/dicom/full_body_ct/1-244.dcm',
//        'wadouri:/dicom/full_body_ct/1-245.dcm',
//        'wadouri:/dicom/full_body_ct/1-246.dcm',
//        'wadouri:/dicom/full_body_ct/1-247.dcm',
//        'wadouri:/dicom/full_body_ct/1-248.dcm',
//        'wadouri:/dicom/full_body_ct/1-249.dcm',
//        'wadouri:/dicom/full_body_ct/1-250.dcm',
//        'wadouri:/dicom/full_body_ct/1-251.dcm',
//        'wadouri:/dicom/full_body_ct/1-252.dcm',
//        'wadouri:/dicom/full_body_ct/1-253.dcm',
//        'wadouri:/dicom/full_body_ct/1-254.dcm',
//        'wadouri:/dicom/full_body_ct/1-255.dcm',
//        'wadouri:/dicom/full_body_ct/1-256.dcm',
//        'wadouri:/dicom/full_body_ct/1-257.dcm',
//        'wadouri:/dicom/full_body_ct/1-258.dcm',
//        'wadouri:/dicom/full_body_ct/1-259.dcm',
//        'wadouri:/dicom/full_body_ct/1-260.dcm',
//        'wadouri:/dicom/full_body_ct/1-261.dcm',
//        'wadouri:/dicom/full_body_ct/1-262.dcm',
//        'wadouri:/dicom/full_body_ct/1-263.dcm',
//        'wadouri:/dicom/full_body_ct/1-264.dcm',
//        'wadouri:/dicom/full_body_ct/1-265.dcm',
//        'wadouri:/dicom/full_body_ct/1-266.dcm',
//        'wadouri:/dicom/full_body_ct/1-267.dcm',
//        'wadouri:/dicom/full_body_ct/1-268.dcm',
//        'wadouri:/dicom/full_body_ct/1-269.dcm',
//        'wadouri:/dicom/full_body_ct/1-270.dcm',
//        'wadouri:/dicom/full_body_ct/1-271.dcm',
//        'wadouri:/dicom/full_body_ct/1-272.dcm',
//        'wadouri:/dicom/full_body_ct/1-273.dcm',
//        'wadouri:/dicom/full_body_ct/1-274.dcm',
//        'wadouri:/dicom/full_body_ct/1-275.dcm',
//        'wadouri:/dicom/full_body_ct/1-276.dcm',
//        'wadouri:/dicom/full_body_ct/1-277.dcm',
//        'wadouri:/dicom/full_body_ct/1-278.dcm',
//        'wadouri:/dicom/full_body_ct/1-279.dcm',
//        'wadouri:/dicom/full_body_ct/1-280.dcm',
//        'wadouri:/dicom/full_body_ct/1-281.dcm',
//        'wadouri:/dicom/full_body_ct/1-282.dcm',
//        'wadouri:/dicom/full_body_ct/1-283.dcm',
//        'wadouri:/dicom/full_body_ct/1-284.dcm',
//        'wadouri:/dicom/full_body_ct/1-285.dcm',
//        'wadouri:/dicom/full_body_ct/1-286.dcm',
//        'wadouri:/dicom/full_body_ct/1-287.dcm',
//        'wadouri:/dicom/full_body_ct/1-288.dcm',
//        'wadouri:/dicom/full_body_ct/1-289.dcm',
//        'wadouri:/dicom/full_body_ct/1-290.dcm',
//        'wadouri:/dicom/full_body_ct/1-291.dcm',
//        'wadouri:/dicom/full_body_ct/1-292.dcm',
//        'wadouri:/dicom/full_body_ct/1-293.dcm',
//        'wadouri:/dicom/full_body_ct/1-294.dcm',
//        'wadouri:/dicom/full_body_ct/1-295.dcm',
//        'wadouri:/dicom/full_body_ct/1-296.dcm',
//        'wadouri:/dicom/full_body_ct/1-297.dcm',
//        'wadouri:/dicom/full_body_ct/1-298.dcm',
//        'wadouri:/dicom/full_body_ct/1-299.dcm',
//        'wadouri:/dicom/full_body_ct/1-300.dcm',
//        'wadouri:/dicom/full_body_ct/1-301.dcm',
//        'wadouri:/dicom/full_body_ct/1-302.dcm',
//        'wadouri:/dicom/full_body_ct/1-303.dcm',
//        'wadouri:/dicom/full_body_ct/1-304.dcm',
//        'wadouri:/dicom/full_body_ct/1-305.dcm',
//        'wadouri:/dicom/full_body_ct/1-306.dcm',
//        'wadouri:/dicom/full_body_ct/1-307.dcm',
//        'wadouri:/dicom/full_body_ct/1-308.dcm',
//        'wadouri:/dicom/full_body_ct/1-309.dcm',
//        'wadouri:/dicom/full_body_ct/1-310.dcm',
//        'wadouri:/dicom/full_body_ct/1-311.dcm',
//        'wadouri:/dicom/full_body_ct/1-312.dcm',
//        'wadouri:/dicom/full_body_ct/1-313.dcm',
//        'wadouri:/dicom/full_body_ct/1-314.dcm',
//        'wadouri:/dicom/full_body_ct/1-315.dcm',
//        'wadouri:/dicom/full_body_ct/1-316.dcm',
//        'wadouri:/dicom/full_body_ct/1-317.dcm',
//        'wadouri:/dicom/full_body_ct/1-318.dcm',
//        'wadouri:/dicom/full_body_ct/1-319.dcm',
//        'wadouri:/dicom/full_body_ct/1-320.dcm',
//        'wadouri:/dicom/full_body_ct/1-321.dcm',
//        'wadouri:/dicom/full_body_ct/1-322.dcm',
//        'wadouri:/dicom/full_body_ct/1-323.dcm',
//        'wadouri:/dicom/full_body_ct/1-324.dcm',
//        'wadouri:/dicom/full_body_ct/1-325.dcm',
//        'wadouri:/dicom/full_body_ct/1-326.dcm',
//        'wadouri:/dicom/full_body_ct/1-327.dcm',
//        'wadouri:/dicom/full_body_ct/1-328.dcm',
//        'wadouri:/dicom/full_body_ct/1-329.dcm',
//        'wadouri:/dicom/full_body_ct/1-330.dcm',
//        'wadouri:/dicom/full_body_ct/1-331.dcm',
//        'wadouri:/dicom/full_body_ct/1-332.dcm',
//        'wadouri:/dicom/full_body_ct/1-333.dcm',
//        'wadouri:/dicom/full_body_ct/1-334.dcm',
//        'wadouri:/dicom/full_body_ct/1-335.dcm',
//        'wadouri:/dicom/full_body_ct/1-336.dcm',
//        'wadouri:/dicom/full_body_ct/1-337.dcm',
//        'wadouri:/dicom/full_body_ct/1-338.dcm',
//        'wadouri:/dicom/full_body_ct/1-339.dcm',
//        'wadouri:/dicom/full_body_ct/1-340.dcm',
//        'wadouri:/dicom/full_body_ct/1-341.dcm',
//        'wadouri:/dicom/full_body_ct/1-342.dcm',
//        'wadouri:/dicom/full_body_ct/1-343.dcm',
//        'wadouri:/dicom/full_body_ct/1-344.dcm',
//        'wadouri:/dicom/full_body_ct/1-345.dcm',
//        'wadouri:/dicom/full_body_ct/1-346.dcm',
//        'wadouri:/dicom/full_body_ct/1-347.dcm',
//        'wadouri:/dicom/full_body_ct/1-348.dcm',
//        'wadouri:/dicom/full_body_ct/1-349.dcm',
//        'wadouri:/dicom/full_body_ct/1-350.dcm',
//        'wadouri:/dicom/full_body_ct/1-351.dcm',
//        'wadouri:/dicom/full_body_ct/1-352.dcm',
//        'wadouri:/dicom/full_body_ct/1-353.dcm',
//        'wadouri:/dicom/full_body_ct/1-354.dcm',
//        'wadouri:/dicom/full_body_ct/1-355.dcm',
//        'wadouri:/dicom/full_body_ct/1-356.dcm',
//        'wadouri:/dicom/full_body_ct/1-357.dcm',
//        'wadouri:/dicom/full_body_ct/1-358.dcm',
//        'wadouri:/dicom/full_body_ct/1-359.dcm',
//        'wadouri:/dicom/full_body_ct/1-360.dcm',
//        'wadouri:/dicom/full_body_ct/1-361.dcm',
//        'wadouri:/dicom/full_body_ct/1-362.dcm',
//        'wadouri:/dicom/full_body_ct/1-363.dcm',
//        'wadouri:/dicom/full_body_ct/1-364.dcm',
//        'wadouri:/dicom/full_body_ct/1-365.dcm',
//        'wadouri:/dicom/full_body_ct/1-366.dcm',
//        'wadouri:/dicom/full_body_ct/1-367.dcm',
//        'wadouri:/dicom/full_body_ct/1-368.dcm',
//        'wadouri:/dicom/full_body_ct/1-369.dcm',
//        'wadouri:/dicom/full_body_ct/1-370.dcm',
//        'wadouri:/dicom/full_body_ct/1-371.dcm',
//        'wadouri:/dicom/full_body_ct/1-372.dcm',
//        'wadouri:/dicom/full_body_ct/1-373.dcm',
//        'wadouri:/dicom/full_body_ct/1-374.dcm',
//        'wadouri:/dicom/full_body_ct/1-375.dcm',
//        'wadouri:/dicom/full_body_ct/1-376.dcm',
//        'wadouri:/dicom/full_body_ct/1-377.dcm',
//        'wadouri:/dicom/full_body_ct/1-378.dcm',
//        'wadouri:/dicom/full_body_ct/1-379.dcm',
//        'wadouri:/dicom/full_body_ct/1-380.dcm',
//        'wadouri:/dicom/full_body_ct/1-381.dcm',
//        'wadouri:/dicom/full_body_ct/1-382.dcm',
//        'wadouri:/dicom/full_body_ct/1-383.dcm',
//        'wadouri:/dicom/full_body_ct/1-384.dcm',
//        'wadouri:/dicom/full_body_ct/1-385.dcm',
//        'wadouri:/dicom/full_body_ct/1-386.dcm',
//        'wadouri:/dicom/full_body_ct/1-387.dcm',
//        'wadouri:/dicom/full_body_ct/1-388.dcm',
//        'wadouri:/dicom/full_body_ct/1-389.dcm',
//        'wadouri:/dicom/full_body_ct/1-390.dcm',
//        'wadouri:/dicom/full_body_ct/1-391.dcm',
//        'wadouri:/dicom/full_body_ct/1-392.dcm',
//        'wadouri:/dicom/full_body_ct/1-393.dcm',
//        'wadouri:/dicom/full_body_ct/1-394.dcm',
//        'wadouri:/dicom/full_body_ct/1-395.dcm',
//        'wadouri:/dicom/full_body_ct/1-396.dcm',
//        'wadouri:/dicom/full_body_ct/1-397.dcm',
//        'wadouri:/dicom/full_body_ct/1-398.dcm',
//        'wadouri:/dicom/full_body_ct/1-399.dcm',
//        'wadouri:/dicom/full_body_ct/1-400.dcm',
//        'wadouri:/dicom/full_body_ct/1-401.dcm',
//        'wadouri:/dicom/full_body_ct/1-402.dcm',
//        'wadouri:/dicom/full_body_ct/1-403.dcm',
//        'wadouri:/dicom/full_body_ct/1-404.dcm',
//        'wadouri:/dicom/full_body_ct/1-405.dcm',
//        'wadouri:/dicom/full_body_ct/1-406.dcm',
//        'wadouri:/dicom/full_body_ct/1-407.dcm',
//        'wadouri:/dicom/full_body_ct/1-408.dcm',
//        'wadouri:/dicom/full_body_ct/1-409.dcm',
//        'wadouri:/dicom/full_body_ct/1-410.dcm',
//        'wadouri:/dicom/full_body_ct/1-411.dcm',
//        'wadouri:/dicom/full_body_ct/1-412.dcm',
//        'wadouri:/dicom/full_body_ct/1-413.dcm',
//        'wadouri:/dicom/full_body_ct/1-414.dcm',
//        'wadouri:/dicom/full_body_ct/1-415.dcm',
//        'wadouri:/dicom/full_body_ct/1-416.dcm',
//        'wadouri:/dicom/full_body_ct/1-417.dcm',
//        'wadouri:/dicom/full_body_ct/1-418.dcm',
//        'wadouri:/dicom/full_body_ct/1-419.dcm',
//        'wadouri:/dicom/full_body_ct/1-420.dcm',
//        'wadouri:/dicom/full_body_ct/1-421.dcm',
//        'wadouri:/dicom/full_body_ct/1-422.dcm',
//        'wadouri:/dicom/full_body_ct/1-423.dcm',
//        'wadouri:/dicom/full_body_ct/1-424.dcm',
//        'wadouri:/dicom/full_body_ct/1-425.dcm',
//        'wadouri:/dicom/full_body_ct/1-426.dcm',
//        'wadouri:/dicom/full_body_ct/1-427.dcm',
//        'wadouri:/dicom/full_body_ct/1-428.dcm',
//        'wadouri:/dicom/full_body_ct/1-429.dcm',
//        'wadouri:/dicom/full_body_ct/1-430.dcm',
//        'wadouri:/dicom/full_body_ct/1-431.dcm',
//        'wadouri:/dicom/full_body_ct/1-432.dcm',
//        'wadouri:/dicom/full_body_ct/1-433.dcm',
//        'wadouri:/dicom/full_body_ct/1-434.dcm',
//        'wadouri:/dicom/full_body_ct/1-435.dcm',
//        'wadouri:/dicom/full_body_ct/1-436.dcm',
//        'wadouri:/dicom/full_body_ct/1-437.dcm',
//        'wadouri:/dicom/full_body_ct/1-438.dcm',
//        'wadouri:/dicom/full_body_ct/1-439.dcm',
//        'wadouri:/dicom/full_body_ct/1-440.dcm',
//        'wadouri:/dicom/full_body_ct/1-441.dcm',
//        'wadouri:/dicom/full_body_ct/1-442.dcm',
//        'wadouri:/dicom/full_body_ct/1-443.dcm',
//        'wadouri:/dicom/full_body_ct/1-444.dcm',
//        'wadouri:/dicom/full_body_ct/1-445.dcm',
//        'wadouri:/dicom/full_body_ct/1-446.dcm',
//        'wadouri:/dicom/full_body_ct/1-447.dcm',
//        'wadouri:/dicom/full_body_ct/1-448.dcm',
//        'wadouri:/dicom/full_body_ct/1-449.dcm',
//        'wadouri:/dicom/full_body_ct/1-450.dcm',
//        'wadouri:/dicom/full_body_ct/1-451.dcm',
//        'wadouri:/dicom/full_body_ct/1-452.dcm',
//        'wadouri:/dicom/full_body_ct/1-453.dcm',
//        'wadouri:/dicom/full_body_ct/1-454.dcm',
//        'wadouri:/dicom/full_body_ct/1-455.dcm',
//        'wadouri:/dicom/full_body_ct/1-456.dcm',
//        'wadouri:/dicom/full_body_ct/1-457.dcm',
//        'wadouri:/dicom/full_body_ct/1-458.dcm',
//        'wadouri:/dicom/full_body_ct/1-459.dcm',
//        'wadouri:/dicom/full_body_ct/1-460.dcm',
//        'wadouri:/dicom/full_body_ct/1-461.dcm',
//        'wadouri:/dicom/full_body_ct/1-462.dcm',
//        'wadouri:/dicom/full_body_ct/1-463.dcm',
//        'wadouri:/dicom/full_body_ct/1-464.dcm',
//        'wadouri:/dicom/full_body_ct/1-465.dcm',
//        'wadouri:/dicom/full_body_ct/1-466.dcm',
//        'wadouri:/dicom/full_body_ct/1-467.dcm',
//        'wadouri:/dicom/full_body_ct/1-468.dcm',
//        'wadouri:/dicom/full_body_ct/1-469.dcm',
//        'wadouri:/dicom/full_body_ct/1-470.dcm',
//        'wadouri:/dicom/full_body_ct/1-471.dcm',
//        'wadouri:/dicom/full_body_ct/1-472.dcm',
//        'wadouri:/dicom/full_body_ct/1-473.dcm',
//        'wadouri:/dicom/full_body_ct/1-474.dcm',
//        'wadouri:/dicom/full_body_ct/1-475.dcm',
//        'wadouri:/dicom/full_body_ct/1-476.dcm',
//        'wadouri:/dicom/full_body_ct/1-477.dcm',
//        'wadouri:/dicom/full_body_ct/1-478.dcm',
//        'wadouri:/dicom/full_body_ct/1-479.dcm',
//        'wadouri:/dicom/full_body_ct/1-480.dcm',
//        'wadouri:/dicom/full_body_ct/1-481.dcm',
//        'wadouri:/dicom/full_body_ct/1-482.dcm',
//        'wadouri:/dicom/full_body_ct/1-483.dcm',
//        'wadouri:/dicom/full_body_ct/1-484.dcm',
//        'wadouri:/dicom/full_body_ct/1-485.dcm',
//        'wadouri:/dicom/full_body_ct/1-486.dcm',
//        'wadouri:/dicom/full_body_ct/1-487.dcm',
//        'wadouri:/dicom/full_body_ct/1-488.dcm',
//        'wadouri:/dicom/full_body_ct/1-489.dcm',
//        'wadouri:/dicom/full_body_ct/1-490.dcm',
//        'wadouri:/dicom/full_body_ct/1-491.dcm',
//        'wadouri:/dicom/full_body_ct/1-492.dcm',
//        'wadouri:/dicom/full_body_ct/1-493.dcm',
//        'wadouri:/dicom/full_body_ct/1-494.dcm',
//        'wadouri:/dicom/full_body_ct/1-495.dcm',
//        'wadouri:/dicom/full_body_ct/1-496.dcm',
//        'wadouri:/dicom/full_body_ct/1-497.dcm',
//        'wadouri:/dicom/full_body_ct/1-498.dcm',
//        'wadouri:/dicom/full_body_ct/1-499.dcm',
//        'wadouri:/dicom/full_body_ct/1-500.dcm',
//        'wadouri:/dicom/full_body_ct/1-501.dcm',
//        'wadouri:/dicom/full_body_ct/1-502.dcm',
//        'wadouri:/dicom/full_body_ct/1-503.dcm',
//        'wadouri:/dicom/full_body_ct/1-504.dcm',
//        'wadouri:/dicom/full_body_ct/1-505.dcm',
//        'wadouri:/dicom/full_body_ct/1-506.dcm',
//        'wadouri:/dicom/full_body_ct/1-507.dcm',
//        'wadouri:/dicom/full_body_ct/1-508.dcm',
//        'wadouri:/dicom/full_body_ct/1-509.dcm',
//        'wadouri:/dicom/full_body_ct/1-510.dcm',
//        'wadouri:/dicom/full_body_ct/1-511.dcm',
//        'wadouri:/dicom/full_body_ct/1-512.dcm',
//        'wadouri:/dicom/full_body_ct/1-513.dcm',
//        'wadouri:/dicom/full_body_ct/1-514.dcm',
//        'wadouri:/dicom/full_body_ct/1-515.dcm',
//        'wadouri:/dicom/full_body_ct/1-516.dcm',
//        'wadouri:/dicom/full_body_ct/1-517.dcm',
//        'wadouri:/dicom/full_body_ct/1-518.dcm',
//        'wadouri:/dicom/full_body_ct/1-519.dcm',
//        'wadouri:/dicom/full_body_ct/1-520.dcm',
//        'wadouri:/dicom/full_body_ct/1-521.dcm',
//        'wadouri:/dicom/full_body_ct/1-522.dcm',
//        'wadouri:/dicom/full_body_ct/1-523.dcm',
//        'wadouri:/dicom/full_body_ct/1-524.dcm',
//        'wadouri:/dicom/full_body_ct/1-525.dcm',
//        'wadouri:/dicom/full_body_ct/1-526.dcm',
//        'wadouri:/dicom/full_body_ct/1-527.dcm',
//        'wadouri:/dicom/full_body_ct/1-528.dcm',
//        'wadouri:/dicom/full_body_ct/1-529.dcm',
//        'wadouri:/dicom/full_body_ct/1-530.dcm',
//        'wadouri:/dicom/full_body_ct/1-531.dcm',
//        'wadouri:/dicom/full_body_ct/1-532.dcm',
//        'wadouri:/dicom/full_body_ct/1-533.dcm',
//        'wadouri:/dicom/full_body_ct/1-534.dcm',
//        'wadouri:/dicom/full_body_ct/1-535.dcm',
//        'wadouri:/dicom/full_body_ct/1-536.dcm',
//        'wadouri:/dicom/full_body_ct/1-537.dcm',
//        'wadouri:/dicom/full_body_ct/1-538.dcm',
//        'wadouri:/dicom/full_body_ct/1-539.dcm',
//        'wadouri:/dicom/full_body_ct/1-540.dcm',
//        'wadouri:/dicom/full_body_ct/1-541.dcm',
//        'wadouri:/dicom/full_body_ct/1-542.dcm',
//        'wadouri:/dicom/full_body_ct/1-543.dcm',
//        'wadouri:/dicom/full_body_ct/1-544.dcm',
//        'wadouri:/dicom/full_body_ct/1-545.dcm',
//        'wadouri:/dicom/full_body_ct/1-546.dcm',
//        'wadouri:/dicom/full_body_ct/1-547.dcm',
//        'wadouri:/dicom/full_body_ct/1-548.dcm',
//        'wadouri:/dicom/full_body_ct/1-549.dcm',
//        'wadouri:/dicom/full_body_ct/1-550.dcm',
//        'wadouri:/dicom/full_body_ct/1-551.dcm',
//        'wadouri:/dicom/full_body_ct/1-552.dcm',
//        'wadouri:/dicom/full_body_ct/1-553.dcm',
//        'wadouri:/dicom/full_body_ct/1-554.dcm',
//        'wadouri:/dicom/full_body_ct/1-555.dcm',
//        'wadouri:/dicom/full_body_ct/1-556.dcm',
//        'wadouri:/dicom/full_body_ct/1-557.dcm',
//        'wadouri:/dicom/full_body_ct/1-558.dcm',
//        'wadouri:/dicom/full_body_ct/1-559.dcm',
//        'wadouri:/dicom/full_body_ct/1-560.dcm',
//        'wadouri:/dicom/full_body_ct/1-561.dcm',
//        'wadouri:/dicom/full_body_ct/1-562.dcm',
//        'wadouri:/dicom/full_body_ct/1-563.dcm',
//        'wadouri:/dicom/full_body_ct/1-564.dcm',
//        'wadouri:/dicom/full_body_ct/1-565.dcm',
//        'wadouri:/dicom/full_body_ct/1-566.dcm',
//        'wadouri:/dicom/full_body_ct/1-567.dcm',
//        'wadouri:/dicom/full_body_ct/1-568.dcm',
//        'wadouri:/dicom/full_body_ct/1-569.dcm',
//        'wadouri:/dicom/full_body_ct/1-570.dcm',
//        'wadouri:/dicom/full_body_ct/1-571.dcm',
//        'wadouri:/dicom/full_body_ct/1-572.dcm',
//        'wadouri:/dicom/full_body_ct/1-573.dcm',
//        'wadouri:/dicom/full_body_ct/1-574.dcm',
//        'wadouri:/dicom/full_body_ct/1-575.dcm',
//        'wadouri:/dicom/full_body_ct/1-576.dcm',
//        'wadouri:/dicom/full_body_ct/1-577.dcm',
//        'wadouri:/dicom/full_body_ct/1-578.dcm',
//        'wadouri:/dicom/full_body_ct/1-579.dcm',
//        'wadouri:/dicom/full_body_ct/1-580.dcm',
//        'wadouri:/dicom/full_body_ct/1-581.dcm',
//        'wadouri:/dicom/full_body_ct/1-582.dcm',
//        'wadouri:/dicom/full_body_ct/1-583.dcm',
//        'wadouri:/dicom/full_body_ct/1-584.dcm',
//        'wadouri:/dicom/full_body_ct/1-585.dcm',
//        'wadouri:/dicom/full_body_ct/1-586.dcm',
//        'wadouri:/dicom/full_body_ct/1-587.dcm',
//        'wadouri:/dicom/full_body_ct/1-588.dcm',
//        'wadouri:/dicom/full_body_ct/1-589.dcm',
//        'wadouri:/dicom/full_body_ct/1-590.dcm',
//        'wadouri:/dicom/full_body_ct/1-591.dcm',
//        'wadouri:/dicom/full_body_ct/1-592.dcm',
//        'wadouri:/dicom/full_body_ct/1-593.dcm',
//        'wadouri:/dicom/full_body_ct/1-594.dcm',
//        'wadouri:/dicom/full_body_ct/1-595.dcm',
//        'wadouri:/dicom/full_body_ct/1-596.dcm',
//        'wadouri:/dicom/full_body_ct/1-597.dcm',
//        'wadouri:/dicom/full_body_ct/1-598.dcm',
//        'wadouri:/dicom/full_body_ct/1-599.dcm',
//        'wadouri:/dicom/full_body_ct/1-600.dcm',
//        'wadouri:/dicom/full_body_ct/1-601.dcm',
//        'wadouri:/dicom/full_body_ct/1-602.dcm',
//        'wadouri:/dicom/full_body_ct/1-603.dcm',
//        'wadouri:/dicom/full_body_ct/1-604.dcm',
//        'wadouri:/dicom/full_body_ct/1-605.dcm',
//        'wadouri:/dicom/full_body_ct/1-606.dcm',
//        'wadouri:/dicom/full_body_ct/1-607.dcm',
//        'wadouri:/dicom/full_body_ct/1-608.dcm',
//        'wadouri:/dicom/full_body_ct/1-609.dcm',
//        'wadouri:/dicom/full_body_ct/1-610.dcm',
//        'wadouri:/dicom/full_body_ct/1-611.dcm',
//        'wadouri:/dicom/full_body_ct/1-612.dcm',
//        'wadouri:/dicom/full_body_ct/1-613.dcm',
//        'wadouri:/dicom/full_body_ct/1-614.dcm',
//        'wadouri:/dicom/full_body_ct/1-615.dcm',
//        'wadouri:/dicom/full_body_ct/1-616.dcm',
//        'wadouri:/dicom/full_body_ct/1-617.dcm',
//        'wadouri:/dicom/full_body_ct/1-618.dcm',
//        'wadouri:/dicom/full_body_ct/1-619.dcm',
//        'wadouri:/dicom/full_body_ct/1-620.dcm',
//        'wadouri:/dicom/full_body_ct/1-621.dcm',
//        'wadouri:/dicom/full_body_ct/1-622.dcm',
//        'wadouri:/dicom/full_body_ct/1-623.dcm',
//        'wadouri:/dicom/full_body_ct/1-624.dcm',
//        'wadouri:/dicom/full_body_ct/1-625.dcm',
//        'wadouri:/dicom/full_body_ct/1-626.dcm',
//        'wadouri:/dicom/full_body_ct/1-627.dcm',
//        'wadouri:/dicom/full_body_ct/1-628.dcm',
//        'wadouri:/dicom/full_body_ct/1-629.dcm',
//        'wadouri:/dicom/full_body_ct/1-630.dcm',
//        'wadouri:/dicom/full_body_ct/1-631.dcm',
//        'wadouri:/dicom/full_body_ct/1-632.dcm',
//        'wadouri:/dicom/full_body_ct/1-633.dcm',
//        'wadouri:/dicom/full_body_ct/1-634.dcm',
//        'wadouri:/dicom/full_body_ct/1-635.dcm',
//        'wadouri:/dicom/full_body_ct/1-636.dcm',
//        'wadouri:/dicom/full_body_ct/1-637.dcm',
//        'wadouri:/dicom/full_body_ct/1-638.dcm',
//        'wadouri:/dicom/full_body_ct/1-639.dcm',
//        'wadouri:/dicom/full_body_ct/1-640.dcm',
//        'wadouri:/dicom/full_body_ct/1-641.dcm',
//        'wadouri:/dicom/full_body_ct/1-642.dcm',
//        'wadouri:/dicom/full_body_ct/1-643.dcm',
//        'wadouri:/dicom/full_body_ct/1-644.dcm',
//        'wadouri:/dicom/full_body_ct/1-645.dcm',
//        'wadouri:/dicom/full_body_ct/1-646.dcm',
//        'wadouri:/dicom/full_body_ct/1-647.dcm',
//        'wadouri:/dicom/full_body_ct/1-648.dcm',
//        'wadouri:/dicom/full_body_ct/1-649.dcm',
//        'wadouri:/dicom/full_body_ct/1-650.dcm',
//        'wadouri:/dicom/full_body_ct/1-651.dcm',
//        'wadouri:/dicom/full_body_ct/1-652.dcm',
//        'wadouri:/dicom/full_body_ct/1-653.dcm',
//        'wadouri:/dicom/full_body_ct/1-654.dcm',
//        'wadouri:/dicom/full_body_ct/1-655.dcm',
//        'wadouri:/dicom/full_body_ct/1-656.dcm',
//        'wadouri:/dicom/full_body_ct/1-657.dcm',
//        'wadouri:/dicom/full_body_ct/1-658.dcm',
//        'wadouri:/dicom/full_body_ct/1-659.dcm',
//        'wadouri:/dicom/full_body_ct/1-660.dcm',
//        'wadouri:/dicom/full_body_ct/1-661.dcm',
//        'wadouri:/dicom/full_body_ct/1-662.dcm',
//        'wadouri:/dicom/full_body_ct/1-663.dcm',
//        'wadouri:/dicom/full_body_ct/1-664.dcm',
//        'wadouri:/dicom/full_body_ct/1-665.dcm',
//        'wadouri:/dicom/full_body_ct/1-666.dcm',
//        'wadouri:/dicom/full_body_ct/1-667.dcm',
//        'wadouri:/dicom/full_body_ct/1-668.dcm',
//        'wadouri:/dicom/full_body_ct/1-669.dcm',
//        'wadouri:/dicom/full_body_ct/1-670.dcm',
//        'wadouri:/dicom/full_body_ct/1-671.dcm',
//        'wadouri:/dicom/full_body_ct/1-672.dcm',
//        'wadouri:/dicom/full_body_ct/1-673.dcm',
//        'wadouri:/dicom/full_body_ct/1-674.dcm',
//        'wadouri:/dicom/full_body_ct/1-675.dcm',
//        'wadouri:/dicom/full_body_ct/1-676.dcm',
//        'wadouri:/dicom/full_body_ct/1-677.dcm',
//        'wadouri:/dicom/full_body_ct/1-678.dcm',
//        'wadouri:/dicom/full_body_ct/1-679.dcm',
//        'wadouri:/dicom/full_body_ct/1-680.dcm',
//        'wadouri:/dicom/full_body_ct/1-681.dcm',
//        'wadouri:/dicom/full_body_ct/1-682.dcm',
//        'wadouri:/dicom/full_body_ct/1-683.dcm',
//        'wadouri:/dicom/full_body_ct/1-684.dcm',
//        'wadouri:/dicom/full_body_ct/1-685.dcm',
//        'wadouri:/dicom/full_body_ct/1-686.dcm',
//        'wadouri:/dicom/full_body_ct/1-687.dcm',
//        'wadouri:/dicom/full_body_ct/1-688.dcm',
//        'wadouri:/dicom/full_body_ct/1-689.dcm',
//        'wadouri:/dicom/full_body_ct/1-690.dcm',
//        'wadouri:/dicom/full_body_ct/1-691.dcm',
//        'wadouri:/dicom/full_body_ct/1-692.dcm',
//        'wadouri:/dicom/full_body_ct/1-693.dcm',
//        'wadouri:/dicom/full_body_ct/1-694.dcm',
//        'wadouri:/dicom/full_body_ct/1-695.dcm',
//        'wadouri:/dicom/full_body_ct/1-696.dcm',
//        'wadouri:/dicom/full_body_ct/1-697.dcm',
//        'wadouri:/dicom/full_body_ct/1-698.dcm',
//        'wadouri:/dicom/full_body_ct/1-699.dcm',
//        'wadouri:/dicom/full_body_ct/1-700.dcm',
//        'wadouri:/dicom/full_body_ct/1-701.dcm',
//        'wadouri:/dicom/full_body_ct/1-702.dcm',
//        'wadouri:/dicom/full_body_ct/1-703.dcm',
//        'wadouri:/dicom/full_body_ct/1-704.dcm',
//        'wadouri:/dicom/full_body_ct/1-705.dcm',
//        'wadouri:/dicom/full_body_ct/1-706.dcm',
//        'wadouri:/dicom/full_body_ct/1-707.dcm',
//        'wadouri:/dicom/full_body_ct/1-708.dcm',
//        'wadouri:/dicom/full_body_ct/1-709.dcm',
//        'wadouri:/dicom/full_body_ct/1-710.dcm',
//        'wadouri:/dicom/full_body_ct/1-711.dcm',
//        'wadouri:/dicom/full_body_ct/1-712.dcm',
//        'wadouri:/dicom/full_body_ct/1-713.dcm',
//        'wadouri:/dicom/full_body_ct/1-714.dcm',
//        'wadouri:/dicom/full_body_ct/1-715.dcm',
//        'wadouri:/dicom/full_body_ct/1-716.dcm',
//        'wadouri:/dicom/full_body_ct/1-717.dcm',
//        'wadouri:/dicom/full_body_ct/1-718.dcm',
//        'wadouri:/dicom/full_body_ct/1-719.dcm',
//        'wadouri:/dicom/full_body_ct/1-720.dcm',
//        'wadouri:/dicom/full_body_ct/1-721.dcm',
//        'wadouri:/dicom/full_body_ct/1-722.dcm',
//        'wadouri:/dicom/full_body_ct/1-723.dcm',
//        'wadouri:/dicom/full_body_ct/1-724.dcm',
//        'wadouri:/dicom/full_body_ct/1-725.dcm',
//        'wadouri:/dicom/full_body_ct/1-726.dcm',
//        'wadouri:/dicom/full_body_ct/1-727.dcm',
//        'wadouri:/dicom/full_body_ct/1-728.dcm',
//        'wadouri:/dicom/full_body_ct/1-729.dcm',
//        'wadouri:/dicom/full_body_ct/1-730.dcm',
//        'wadouri:/dicom/full_body_ct/1-731.dcm',
//        'wadouri:/dicom/full_body_ct/1-732.dcm',
//        'wadouri:/dicom/full_body_ct/1-733.dcm',
//        'wadouri:/dicom/full_body_ct/1-734.dcm',
//        'wadouri:/dicom/full_body_ct/1-735.dcm',
//        'wadouri:/dicom/full_body_ct/1-736.dcm',
//        'wadouri:/dicom/full_body_ct/1-737.dcm',
//        'wadouri:/dicom/full_body_ct/1-738.dcm',
//        'wadouri:/dicom/full_body_ct/1-739.dcm',
//        'wadouri:/dicom/full_body_ct/1-740.dcm',
//        'wadouri:/dicom/full_body_ct/1-741.dcm',
//        'wadouri:/dicom/full_body_ct/1-742.dcm',
//        'wadouri:/dicom/full_body_ct/1-743.dcm',
//        'wadouri:/dicom/full_body_ct/1-744.dcm',
//        'wadouri:/dicom/full_body_ct/1-745.dcm',
//        'wadouri:/dicom/full_body_ct/1-746.dcm',
//        'wadouri:/dicom/full_body_ct/1-747.dcm',
//        'wadouri:/dicom/full_body_ct/1-748.dcm',
//        'wadouri:/dicom/full_body_ct/1-749.dcm',
//        'wadouri:/dicom/full_body_ct/1-750.dcm',
//        'wadouri:/dicom/full_body_ct/1-751.dcm',
//        'wadouri:/dicom/full_body_ct/1-752.dcm',
//        'wadouri:/dicom/full_body_ct/1-753.dcm',
//        'wadouri:/dicom/full_body_ct/1-754.dcm',
//        'wadouri:/dicom/full_body_ct/1-755.dcm',
//        'wadouri:/dicom/full_body_ct/1-756.dcm',
//        'wadouri:/dicom/full_body_ct/1-757.dcm',
//        'wadouri:/dicom/full_body_ct/1-758.dcm',
//        'wadouri:/dicom/full_body_ct/1-759.dcm',
//        'wadouri:/dicom/full_body_ct/1-760.dcm',
//        'wadouri:/dicom/full_body_ct/1-761.dcm',
//        'wadouri:/dicom/full_body_ct/1-762.dcm',
//        'wadouri:/dicom/full_body_ct/1-763.dcm',
//        'wadouri:/dicom/full_body_ct/1-764.dcm',
//        'wadouri:/dicom/full_body_ct/1-765.dcm',
//        'wadouri:/dicom/full_body_ct/1-766.dcm',
//        'wadouri:/dicom/full_body_ct/1-767.dcm',
//        'wadouri:/dicom/full_body_ct/1-768.dcm',
//        'wadouri:/dicom/full_body_ct/1-769.dcm',
//        'wadouri:/dicom/full_body_ct/1-770.dcm',
//        'wadouri:/dicom/full_body_ct/1-771.dcm',
//        'wadouri:/dicom/full_body_ct/1-772.dcm',
//        'wadouri:/dicom/full_body_ct/1-773.dcm',
//        'wadouri:/dicom/full_body_ct/1-774.dcm',
//        'wadouri:/dicom/full_body_ct/1-775.dcm',
//        'wadouri:/dicom/full_body_ct/1-776.dcm',
//        'wadouri:/dicom/full_body_ct/1-777.dcm',
//        'wadouri:/dicom/full_body_ct/1-778.dcm',
//        'wadouri:/dicom/full_body_ct/1-779.dcm',
//        'wadouri:/dicom/full_body_ct/1-780.dcm',
//        'wadouri:/dicom/full_body_ct/1-781.dcm',
//        'wadouri:/dicom/full_body_ct/1-782.dcm',
//        'wadouri:/dicom/full_body_ct/1-783.dcm',
//        'wadouri:/dicom/full_body_ct/1-784.dcm',
//        'wadouri:/dicom/full_body_ct/1-785.dcm',
//        'wadouri:/dicom/full_body_ct/1-786.dcm',
//        'wadouri:/dicom/full_body_ct/1-787.dcm',
//        'wadouri:/dicom/full_body_ct/1-788.dcm',
//        'wadouri:/dicom/full_body_ct/1-789.dcm',
//        'wadouri:/dicom/full_body_ct/1-790.dcm',
//        'wadouri:/dicom/full_body_ct/1-791.dcm',
//        'wadouri:/dicom/full_body_ct/1-792.dcm',
//        'wadouri:/dicom/full_body_ct/1-793.dcm',
//        'wadouri:/dicom/full_body_ct/1-794.dcm',
//        'wadouri:/dicom/full_body_ct/1-795.dcm',
//        'wadouri:/dicom/full_body_ct/1-796.dcm',
//        'wadouri:/dicom/full_body_ct/1-797.dcm',
//        'wadouri:/dicom/full_body_ct/1-798.dcm',
//        'wadouri:/dicom/full_body_ct/1-799.dcm',
//        'wadouri:/dicom/full_body_ct/1-800.dcm',
//        'wadouri:/dicom/full_body_ct/1-801.dcm',
//        'wadouri:/dicom/full_body_ct/1-802.dcm',
//        'wadouri:/dicom/full_body_ct/1-803.dcm',
//        'wadouri:/dicom/full_body_ct/1-804.dcm',
//        'wadouri:/dicom/full_body_ct/1-805.dcm',
//        'wadouri:/dicom/full_body_ct/1-806.dcm',
//        'wadouri:/dicom/full_body_ct/1-807.dcm',
//        'wadouri:/dicom/full_body_ct/1-808.dcm',
//        'wadouri:/dicom/full_body_ct/1-809.dcm',
//        'wadouri:/dicom/full_body_ct/1-810.dcm',
//        'wadouri:/dicom/full_body_ct/1-811.dcm',
//        'wadouri:/dicom/full_body_ct/1-812.dcm',
//        'wadouri:/dicom/full_body_ct/1-813.dcm',
//        'wadouri:/dicom/full_body_ct/1-814.dcm',
//        'wadouri:/dicom/full_body_ct/1-815.dcm',
//        'wadouri:/dicom/full_body_ct/1-816.dcm',
//        'wadouri:/dicom/full_body_ct/1-817.dcm',
//        'wadouri:/dicom/full_body_ct/1-818.dcm',
//        'wadouri:/dicom/full_body_ct/1-819.dcm',
//        'wadouri:/dicom/full_body_ct/1-820.dcm',
//        'wadouri:/dicom/full_body_ct/1-821.dcm',
//        'wadouri:/dicom/full_body_ct/1-822.dcm',
//        'wadouri:/dicom/full_body_ct/1-823.dcm',
//        'wadouri:/dicom/full_body_ct/1-824.dcm',
//        'wadouri:/dicom/full_body_ct/1-825.dcm',
//        'wadouri:/dicom/full_body_ct/1-826.dcm',
//        'wadouri:/dicom/full_body_ct/1-827.dcm',
//        'wadouri:/dicom/full_body_ct/1-828.dcm',
//    ];
//}//}}}

function getDICOMVolume() {//{{{
    return [
        'wadouri:/dicom/breast_with_seg/volume/1-001.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-002.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-003.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-004.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-005.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-006.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-007.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-008.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-009.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-010.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-011.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-012.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-013.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-014.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-015.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-016.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-017.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-018.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-019.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-020.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-021.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-022.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-023.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-024.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-025.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-026.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-027.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-028.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-029.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-030.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-031.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-032.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-033.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-034.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-035.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-036.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-037.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-038.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-039.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-040.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-041.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-042.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-043.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-044.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-045.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-046.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-047.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-048.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-049.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-050.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-051.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-052.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-053.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-054.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-055.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-056.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-057.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-058.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-059.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-060.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-061.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-062.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-063.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-064.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-065.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-066.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-067.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-068.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-069.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-070.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-071.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-072.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-073.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-074.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-075.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-076.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-077.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-078.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-079.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-080.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-081.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-082.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-083.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-084.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-085.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-086.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-087.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-088.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-089.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-090.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-091.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-092.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-093.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-094.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-095.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-096.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-097.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-098.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-099.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-100.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-101.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-102.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-103.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-104.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-105.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-106.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-107.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-108.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-109.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-110.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-111.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-112.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-113.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-114.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-115.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-116.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-117.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-118.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-119.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-120.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-121.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-122.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-123.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-124.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-125.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-126.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-127.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-128.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-129.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-130.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-131.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-132.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-133.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-134.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-135.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-136.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-137.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-138.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-139.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-140.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-141.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-142.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-143.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-144.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-145.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-146.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-147.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-148.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-149.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-150.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-151.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-152.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-153.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-154.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-155.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-156.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-157.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-158.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-159.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-160.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-161.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-162.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-163.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-164.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-165.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-166.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-167.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-168.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-169.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-170.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-171.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-172.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-173.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-174.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-175.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-176.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-177.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-178.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-179.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-180.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-181.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-182.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-183.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-184.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-185.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-186.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-187.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-188.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-189.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-190.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-191.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-192.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-193.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-194.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-195.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-196.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-197.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-198.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-199.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-200.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-201.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-202.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-203.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-204.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-205.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-206.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-207.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-208.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-209.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-210.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-211.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-212.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-213.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-214.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-215.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-216.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-217.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-218.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-219.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-220.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-221.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-222.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-223.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-224.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-225.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-226.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-227.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-228.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-229.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-230.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-231.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-232.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-233.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-234.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-235.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-236.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-237.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-238.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-239.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-240.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-241.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-242.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-243.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-244.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-245.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-246.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-247.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-248.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-249.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-250.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-251.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-252.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-253.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-254.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-255.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-256.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-257.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-258.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-259.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-260.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-261.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-262.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-263.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-264.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-265.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-266.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-267.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-268.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-269.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-270.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-271.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-272.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-273.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-274.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-275.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-276.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-277.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-278.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-279.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-280.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-281.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-282.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-283.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-284.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-285.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-286.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-287.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-288.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-289.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-290.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-291.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-292.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-293.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-294.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-295.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-296.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-297.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-298.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-299.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-300.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-301.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-302.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-303.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-304.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-305.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-306.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-307.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-308.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-309.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-310.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-311.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-312.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-313.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-314.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-315.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-316.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-317.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-318.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-319.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-320.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-321.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-322.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-323.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-324.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-325.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-326.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-327.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-328.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-329.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-330.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-331.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-332.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-333.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-334.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-335.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-336.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-337.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-338.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-339.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-340.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-341.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-342.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-343.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-344.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-345.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-346.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-347.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-348.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-349.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-350.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-351.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-352.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-353.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-354.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-355.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-356.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-357.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-358.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-359.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-360.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-361.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-362.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-363.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-364.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-365.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-366.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-367.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-368.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-369.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-370.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-371.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-372.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-373.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-374.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-375.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-376.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-377.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-378.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-379.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-380.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-381.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-382.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-383.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-384.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-385.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-386.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-387.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-388.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-389.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-390.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-391.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-392.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-393.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-394.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-395.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-396.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-397.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-398.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-399.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-400.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-401.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-402.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-403.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-404.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-405.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-406.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-407.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-408.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-409.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-410.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-411.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-412.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-413.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-414.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-415.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-416.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-417.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-418.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-419.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-420.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-421.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-422.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-423.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-424.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-425.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-426.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-427.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-428.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-429.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-430.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-431.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-432.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-433.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-434.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-435.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-436.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-437.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-438.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-439.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-440.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-441.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-442.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-443.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-444.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-445.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-446.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-447.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-448.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-449.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-450.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-451.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-452.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-453.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-454.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-455.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-456.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-457.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-458.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-459.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-460.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-461.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-462.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-463.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-464.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-465.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-466.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-467.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-468.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-469.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-470.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-471.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-472.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-473.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-474.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-475.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-476.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-477.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-478.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-479.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-480.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-481.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-482.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-483.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-484.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-485.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-486.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-487.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-488.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-489.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-490.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-491.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-492.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-493.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-494.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-495.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-496.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-497.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-498.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-499.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-500.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-501.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-502.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-503.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-504.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-505.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-506.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-507.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-508.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-509.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-510.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-511.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-512.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-513.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-514.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-515.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-516.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-517.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-518.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-519.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-520.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-521.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-522.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-523.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-524.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-525.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-526.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-527.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-528.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-529.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-530.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-531.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-532.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-533.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-534.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-535.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-536.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-537.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-538.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-539.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-540.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-541.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-542.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-543.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-544.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-545.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-546.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-547.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-548.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-549.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-550.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-551.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-552.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-553.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-554.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-555.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-556.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-557.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-558.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-559.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-560.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-561.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-562.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-563.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-564.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-565.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-566.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-567.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-568.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-569.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-570.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-571.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-572.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-573.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-574.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-575.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-576.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-577.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-578.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-579.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-580.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-581.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-582.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-583.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-584.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-585.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-586.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-587.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-588.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-589.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-590.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-591.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-592.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-593.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-594.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-595.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-596.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-597.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-598.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-599.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-600.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-601.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-602.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-603.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-604.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-605.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-606.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-607.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-608.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-609.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-610.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-611.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-612.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-613.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-614.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-615.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-616.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-617.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-618.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-619.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-620.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-621.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-622.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-623.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-624.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-625.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-626.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-627.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-628.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-629.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-630.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-631.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-632.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-633.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-634.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-635.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-636.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-637.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-638.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-639.dcm',
        'wadouri:/dicom/breast_with_seg/volume/1-640.dcm',
    ];
}//}}}

function getDICOMSeg() {//{{{
    return [
        'wadouri:/dicom/breast_with_seg/seg/1-1.dcm',
    ];
}//}}}


run('NIFTI');
//run('DICOM');